apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  namespace: platform
  labels:
    app: ui-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-service
  template:
    metadata:
      labels:
        app: ui-service
    spec:
      nodeSelector:
        role: platform
      containers:
      - name: ui-service-container
        image: gsiatras13/digital_platform-ui_service:a1.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_URL
          value: "postgresql://platform:platform1234@postgres-service:5432/platform"