apiVersion: v1
kind: Service
metadata:
  name: manager-service
  namespace: platform
spec:
  selector:
    app: manager-service
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
  type: ClusterIP 