apiVersion: v1
kind: Service
metadata:
  name: worker-service
  namespace: platform
spec:
  selector:
    app: worker-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP 